#!/usr/bin/env bash
# Script that configures localhost and facebook.com IP resolution

# Change localhost to resolve to 127.0.0.2
sed -i 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2\tlocalhost/' /etc/hosts

# Make facebook.com resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
